version: '3'

services:
  # A PostgreSQL database for the Broker to store Pacts and verification results
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  # The Pact Broker
  broker_app:
    # Alternatively the DiUS Pact Broker can be used:
    # image: dius/pact-broker
    #
    # As well as changing the image, the destination port will need to be changed
    # from 9292 below, and in the nginx.conf proxy_pass section
    image: pactfoundation/pact-broker:2.89.0.0
    ports:
      - "80:9292"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker

  # An NGINX reverse proxy in front of the Broker on port 8443, to be able to
  # terminate with SSL
  nginx:
    image: nginx:alpine
    links:
      - broker_app:broker
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8443:443"
